// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedagangPulsa.API.Database;

#nullable disable

namespace PedagangPulsa.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241013124823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CallbackPaymentDuitku", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fee")
                        .HasColumnType("int");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("statusCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("statusMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("CallbackPaymentDuitku");
                });

            modelBuilder.Entity("PedagangPulsa.API.Database.Entity.DetailProduk", b =>
                {
                    b.Property<int>("ProdukID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProdukID"));

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ProdukID");

                    b.ToTable("DetailProduk");
                });

            modelBuilder.Entity("PedagangPulsa.API.Database.Entity.KategoriProduk", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KategoriID");

                    b.ToTable("KategoriProduk");
                });

            modelBuilder.Entity("PedagangPulsa.API.Database.Entity.Produk", b =>
                {
                    b.Property<string>("Vendor")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Kode")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("Kategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deskripsi_produk")
                        .HasColumnType("longtext");

                    b.Property<int>("kategory_Id")
                        .HasColumnType("int");

                    b.Property<string>("nama_produk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Vendor", "Kode");

                    b.ToTable("Produk");
                });

            modelBuilder.Entity("PedagangPulsa.API.Database.Entity.Transaksi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("IdPembeli")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TanggalKonfirmasi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("harga_agen")
                        .HasColumnType("int");

                    b.Property<int?>("harga_jual")
                        .HasColumnType("int");

                    b.Property<int>("id_vendor")
                        .HasColumnType("int");

                    b.Property<string>("kode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nama_produk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("no_tujuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sn")
                        .HasColumnType("longtext");

                    b.Property<string>("status_transaksi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Transaksi");
                });

            modelBuilder.Entity("PedagangPulsa.API.Database.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsVerived")
                        .HasColumnType("int");

                    b.Property<string>("LastOTP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastTransaksi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoWA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PinTransaksi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Saldo")
                        .HasColumnType("int");

                    b.Property<string>("Telegram")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
